FROM python

RUN useradd -ms /bin/bash bacchilu
USER bacchilu

WORKDIR /app

COPY requirements.txt .

RUN pip3 install -r requirements.txt

COPY . .

ENV FLASK_APP=server.py
ENV FLASK_DEBUG=1

EXPOSE 5000

CMD flask run --host=0.0.0.0
