FROM python
LABEL maintainer="Luca Bacchi <bacchilu@gmail.com> (https://github.com/bacchilu)"

WORKDIR /app

ARG UID
ARG GID
ARG MODE=PROD

RUN groupadd -g "${GID}" python
RUN useradd --create-home --no-log-init -u "${UID}" -g "${GID}" python
RUN chown python:python -R /app

USER python

COPY --chown=python:python requirements.txt .

RUN pip3 install -r requirements.txt

ENV PYTHONPATH="."
ENV PATH="${PATH}:/home/python/.local/bin"
ENV USER="python"
ENV MODE="${MODE}"

COPY --chown=python:python ./src .

ARG FLASK_DEBUG=0

ENV FLASK_APP=src/server.py
ENV FLASK_DEBUG=${FLASK_DEBUG}

EXPOSE 5000

CMD flask run --host=0.0.0.0
