services:
  flask-prod:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=PROD"
    ports:
      - '80:8000'
    env_file: .env
    restart: unless-stopped
  flask-dev:
    build:
      context: ./
      dockerfile: Dockerfile.dev
      args:
        - "UID=${UID}"
        - "GID=${GID}"
        - "MODE=DEV"
    ports:
      - '5000:5000'
    volumes:
      - ./src:/app
    env_file: .env
