FROM python

COPY requirements.txt .

RUN pip3 install -r requirements.txt

ARG USER_ID
RUN useradd -ms /bin/bash USER_ID
USER USER_ID

WORKDIR /app

COPY . .

ENV FLASK_APP=server.py
ENV FLASK_DEBUG=1

EXPOSE 5000

CMD flask run --host=0.0.0.0
